services: # Can run docker-compose up in the play button in this line.
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres #Where to store data
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432" #5432 is default Posgress port
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes: # define volume
  db: